# Generated by Django 4.0.4 on 2022-12-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='id',
            new_name='device_id',
        ),
    ]
