# Generated by Django 4.0.4 on 2023-01-12 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_ip_device_wifi_pwd_device_wifi_ssid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='devices/static/assets/img/floors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='wifi_pwd',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='wifi_ssid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='data',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Device_Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw', models.CharField(max_length=250)),
                ('shape', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idDevice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.floor')),
                ('idFloor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
        ),
    ]
