# Generated by Django 4.0.4 on 2023-01-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_floor_alter_device_device_id_alter_device_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='coordinates',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
