# Generated by Django 4.0.4 on 2023-01-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_firewall_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='qos_filters',
            name='filterHandle',
            field=models.CharField(default='803::800', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qos_filters',
            name='filterType',
            field=models.CharField(default='u32', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qos_filters',
            name='interface',
            field=models.CharField(default='wlan0', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qos_filters',
            name='priority',
            field=models.CharField(default='49149', max_length=100),
            preserve_default=False,
        ),
    ]
