# Generated by Django 4.0.4 on 2023-01-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_qos_filters_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qos_filters',
            name='rule',
        ),
        migrations.AddField(
            model_name='qos_filters',
            name='rule_name',
            field=models.CharField(default='1:20', max_length=100),
            preserve_default=False,
        ),
    ]
