from django.db import models

class Device(models.Model):
    # device_id = models.CharField(primary_key=True,auto_created=True,max_length=100) # ID em formato de texto
    device_id = models.AutoField(primary_key=True, auto_created=True)
    name = models.CharField(max_length=100)
    mac_address = models.CharField(max_length=30)
    status = models.BooleanField(default=True)
    type = models.CharField(max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    #artist = models.ForeignKey(Musician, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class CreateDevice(models.Model):
    text = models.CharField(max_length=244, default='travel')
    device_id = models.ForeignKey(Device, on_delete=models.CASCADE, related_name='ids')

# class Member(models.Model):
    # """A model of a rock band member."""
    # name = models.CharField("Member's name", max_length=200)
    # type = models.CharField(choices=(
            # ('g', "Guitar"),
            # ('b', "Bass"),
            # ('d', "Drums"),
        # ),
        # max_length=1
    # )
    # status = models.CharField("Member's name", max_length=200)
    # band = models.ForeignKey("Band")

# SQL
# CREATE TABLE device (
# 	"device_id" serial NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
# 	"mac_address" varchar(30) NOT NULL,
# 	"name" varchar(100),
# 	"type" varchar(30),
# 	"status" integer,
# 	"createdAt" timestamp with time zone default now_utc(),
# 	"updatedAt" timestamp with time zone default now_utc(),
# );